# Generated by Django 5.2.17 on 2026-09-17 02:30

import conteineres.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('documento', models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conteiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(help_text='Código ISO 6346, ex.: CSQU3054383', max_length=11, unique=True, validators=[conteineres.validators.validar_numero_conteiner], verbose_name='número')),
                ('tipo', models.CharField(choices=[('20', '20 pés'), ('40', '40 pés')], max_length=2, verbose_name='tipo')),
                ('status', models.CharField(choices=[('cheio', 'Cheio'), ('vazio', 'Vazio')], max_length=5, verbose_name='status')),
                ('categoria', models.CharField(choices=[('importacao', 'Importação'), ('exportacao', 'Exportação')], max_length=10, verbose_name='categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteineres', to='conteineres.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'contêiner',
                'verbose_name_plural': 'contêineres',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('embarque', 'Embarque'), ('desembarque', 'Desembarque'), ('gate_in', 'Gate In'), ('gate_out', 'Gate Out'), ('reposicionamento', 'Reposicionamento'), ('pesagem', 'Pesagem'), ('scanner', 'Scanner')], max_length=20, verbose_name='tipo')),
                ('data_inicio', models.DateTimeField(verbose_name='início')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Deixe em branco se estiver em andamento.', null=True, verbose_name='fim')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('conteiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='conteineres.conteiner', verbose_name='contêiner')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='conteiner',
            index=models.Index(fields=['status', 'categoria'], name='conteineres_status_46ff63_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='movimentacao_fim_apos_inicio'),
        ),
    ]
